### ISSUE TITLE
CI fails with 4 Gingko runners

### ISSUE THREAD

**Issue by kkaempf** [SUSE/carrier#221] opened 2021-03-15 18:04 UTC
See https://github.com/SUSE/carrier/actions/runs/654956612.
Fails during `doesn't delete a bound service [It]`

Previous runs (with 2 Ginkgo runners) were successful.

@andreas-kupries :point_up_2: :wink:

**Comment by kkaempf** [comment] 2021-03-15 18:05
Log snippet

```
[1] STEP: targeting an org
[1] • Failure [151.191 seconds]
[1] Catalog Services
[1] /home/carrier/actions-runner/_work/carrier/carrier/acceptance/catalog_services_test.go:8
[1]   delete service
[1]   /home/carrier/actions-runner/_work/carrier/carrier/acceptance/catalog_services_test.go:31
[1]     doesn't delete a bound service [It]
[1]     /home/carrier/actions-runner/_work/carrier/carrier/acceptance/catalog_services_test.go:40
[1] 
[1]     Expected
[1]         <string>: W0315 18:08:52.609409   27901 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
[1]         
[1]         🚢 Delete Service
[1]         Name: service-868141208
[1]         Organization: apps-org
[1]         
[1]         🚢 Unbinding Service From Using Applications Before Deletion
[1]         | BOUND APPLICATIONS |
[1]         |--------------------|
[1]         | apps-565457773     |
[1]         
[1]         ⚠️  Hit Enter to continue or Ctrl+C to abort (removal will continue automatically in 5 seconds)
[1]         
[1]         🚢 Unbinding
[1]         Application: apps-565457773
[1]         
[1]         ⚠️  Operation cannot be fulfilled on deployments.apps "apps-org.apps-565457773": the object has been modified; please apply your changes to the latest version and try again
[1]         
[1]         🚢 Back to deleting the service...
[1]         
[1]         ✔️  Service Removed.
[1]         Name: service-868141208
[1]         Organization: apps-org
[1]         
[1]     to match regular expression
[1]         <string>: Unbound
[1] 
[1]     /home/carrier/go/pkg/mod/github.com/onsi/gomega@v1.10.3/internal/assertion/assertion.go:38
```

**Comment by andreas-kupries** [comment] 2021-03-16 08:06
Ok ... The `Operation cannot be fulfilled on deployments.apps "apps-org.apps-565457773": the object has been modified; please apply your changes to the latest version and try again` points to the `Update` operation on the deployment failing ...

File `internal/application/applicationg.go`, func `Unbind`, line 106 ...
And the `Get` happens at the very beginning of that function.

So in between the `Get` and `Update`, where the code modifies the object some other client did their own modification on the same deployment, leaving the in-memory copy out of date ...

Classical race between multiple instances of the cli ... Although a bit unclear why two different cli's should/would try to modify the same app. At least in the tests. In real life I can see that happen.

Fix, I believe, would be to

 - Detect this specific error, and
 - Loop the code, i.e. refetch the object, re-modify, and try the update again.

Maybe limit to ... 10 times ... and then giving up.

And the `Bind` function has the same issue.

**Comment by kkaempf** [comment] 2021-03-16 12:57
It's clearly a race condition. A subsequent run with 4 nodes [finished successful](https://github.com/SUSE/carrier/issues/217#issuecomment-800233270).

**Comment by andreas-kupries** [comment] 2021-03-16 14:50
Fixed by #223

**Comment by andreas-kupries** [comment] 2021-03-16 14:54
Managed to to repro using 2 concurrently running instances of
```
#!/bin/bash
set -xe
while true
do
    carrier unbind-service world hello
    carrier bind-service   world hello
done
```

One would work fine, and the other quickly run into the conflict.

With the change one or the other fails with service already (unbound), i.e. the action in conflict then detected that the other action had done the work for it.

This can still generate an error in the 🐈 , but the error is not a bug anymore.
The bug is then in the 🐈 somehow accessing the same app from different tests.
I believe that part should be handled in a separate PR.

**Closed** 2021-03-16 16:47 UTC
Labels: bug

**Comment by jimmykarily** [comment] 2021-03-17 08:26
A deployment could be changed in the cluster by various events, even ones not triggered through the carrier cli I think. iiuc anything that updates the Deployment (e.g. how many available instances are there or other field in its status) would change the version of the Deployment that we have in memore and this would result in a failed update. Re-trying should be the right thing to do (like the PR does),
